[workspace]
members = [
    "crates/tencir-pauli-core",
    "crates/tencirpauli-native",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"
authors = ["refraction-ray <znfesnpbh@gmail.com>"]
repository = "https://github.com/tensorcircuit/TenCirPauli"
homepage = "https://github.com/tensorcircuit/TenCirPauli"

[workspace.dependencies]
pyo3 = { version = "0.23.5", features = ["abi3-py39", "extension-module"] }
