from typing import Any, Sequence

__version__: str

class StructuredMvpPlan:
    @property
    def dimension(self) -> int: ...
    @property
    def estimated_bytes(self) -> int: ...
    def apply(self, state: object, max_bytes: int) -> object: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...

class NativePauliOperatorHandle:
    @property
    def nqubits(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    def distinct_x_mask_count(self) -> int: ...
    def add(
        self, other: "NativePauliOperatorHandle", max_bytes: int
    ) -> "NativePauliOperatorHandle": ...
    def scale(
        self, scalar_re: float, scalar_im: float
    ) -> "NativePauliOperatorHandle": ...
    def multiply(
        self, other: "NativePauliOperatorHandle", max_bytes: int
    ) -> "NativePauliOperatorHandle": ...
    def commutator(
        self, other: "NativePauliOperatorHandle", max_bytes: int
    ) -> "NativePauliOperatorHandle": ...
    def anticommutator(
        self, other: "NativePauliOperatorHandle", max_bytes: int
    ) -> "NativePauliOperatorHandle": ...
    def materialize(
        self,
    ) -> tuple[int, int, object, object, object]: ...
    def materialize_arrays(
        self,
    ) -> tuple[int, int, object, object]: ...
    def materialize_strings(
        self,
    ) -> tuple[Sequence[str], object]: ...
    def adjoint(self) -> "NativePauliOperatorHandle": ...
    def is_hermitian(self, tolerance: float) -> bool: ...
    def termwise_conserves_charge(
        self, qubit_levels: Sequence[tuple[float, float]]
    ) -> bool: ...
    def content_eq(self, other: "NativePauliOperatorHandle") -> bool: ...
    def content_hash(self) -> int: ...

class NativeFermionOperatorHandle:
    @property
    def n_modes(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    def add(
        self, other: "NativeFermionOperatorHandle", max_bytes: int
    ) -> "NativeFermionOperatorHandle": ...
    def scale(
        self, scalar_re: float, scalar_im: float
    ) -> "NativeFermionOperatorHandle": ...
    def multiply(
        self, other: "NativeFermionOperatorHandle", max_bytes: int
    ) -> "NativeFermionOperatorHandle": ...
    def adjoint(self, max_bytes: int) -> "NativeFermionOperatorHandle": ...
    def jordan_wigner(self, max_bytes: int) -> "NativePauliOperatorHandle": ...
    def commutator(
        self, other: "NativeFermionOperatorHandle", max_bytes: int
    ) -> "NativeFermionOperatorHandle": ...
    def anticommutator(
        self, other: "NativeFermionOperatorHandle", max_bytes: int
    ) -> "NativeFermionOperatorHandle": ...
    def to_majorana(self, max_bytes: int) -> "NativeMajoranaOperatorHandle": ...
    def to_hybrid(self) -> "NativeHybridOperatorHandle": ...
    def is_hermitian(self, tolerance: float) -> bool: ...
    def content_eq(self, other: "NativeFermionOperatorHandle") -> bool: ...
    def content_hash(self) -> int: ...
    def materialize(
        self,
    ) -> tuple[int, object, object, object, object, object]: ...

class NativeBosonOperatorHandle:
    @property
    def n_modes(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    def add(
        self, other: "NativeBosonOperatorHandle", max_bytes: int
    ) -> "NativeBosonOperatorHandle": ...
    def scale(
        self, scalar_re: float, scalar_im: float
    ) -> "NativeBosonOperatorHandle": ...
    def multiply(
        self, other: "NativeBosonOperatorHandle", max_bytes: int
    ) -> "NativeBosonOperatorHandle": ...
    def adjoint(self) -> "NativeBosonOperatorHandle": ...
    def commutator(
        self, other: "NativeBosonOperatorHandle", max_bytes: int
    ) -> "NativeBosonOperatorHandle": ...
    def anticommutator(
        self, other: "NativeBosonOperatorHandle", max_bytes: int
    ) -> "NativeBosonOperatorHandle": ...
    def to_hybrid(self) -> "NativeHybridOperatorHandle": ...
    def is_hermitian(self, tolerance: float) -> bool: ...
    def content_eq(self, other: "NativeBosonOperatorHandle") -> bool: ...
    def content_hash(self) -> int: ...
    def materialize(
        self,
    ) -> tuple[int, object, object, object]: ...

class NativeHybridOperatorHandle:
    @property
    def term_count(self) -> int: ...
    def has_raw_fermions(self) -> bool: ...
    def has_mapped_fermions(self) -> bool: ...
    def has_mixed_fermion_roles(self) -> bool: ...
    def add(
        self, other: "NativeHybridOperatorHandle", max_bytes: int
    ) -> "NativeHybridOperatorHandle": ...
    def scale(
        self, scalar_re: float, scalar_im: float
    ) -> "NativeHybridOperatorHandle": ...
    def multiply(
        self, other: "NativeHybridOperatorHandle", max_bytes: int
    ) -> "NativeHybridOperatorHandle": ...
    def jordan_wigner(self, max_bytes: int) -> "NativeHybridOperatorHandle": ...
    def adjoint(self) -> "NativeHybridOperatorHandle": ...
    def commutator(
        self, other: "NativeHybridOperatorHandle", max_bytes: int
    ) -> "NativeHybridOperatorHandle": ...
    def anticommutator(
        self, other: "NativeHybridOperatorHandle", max_bytes: int
    ) -> "NativeHybridOperatorHandle": ...
    def to_pauli(
        self, axes: Sequence[tuple[int, int]], max_bytes: int
    ) -> "NativePauliOperatorHandle": ...
    def to_fermion(self) -> "NativeFermionOperatorHandle": ...
    def to_boson(self) -> "NativeBosonOperatorHandle": ...
    def embed(
        self,
        target_n_modes: int,
        target_n_bosons: int,
        target_nqubits: int,
        target_n_qudit_sites: int,
        target_qudit_dimension: int,
        fermion_map: Sequence[int],
        boson_map: Sequence[int],
        qubit_map: Sequence[int],
        qudit_map: Sequence[int],
        max_bytes: int,
    ) -> "NativeHybridOperatorHandle": ...
    def analyze_charge(
        self,
        fermion_weights: Sequence[float],
        boson_weights: Sequence[float],
        qubit_levels: Sequence[tuple[float, float]],
        max_bytes: int,
    ) -> tuple[bool, int]: ...
    def termwise_conserves_charge(
        self,
        fermion_weights: Sequence[float],
        boson_weights: Sequence[float],
        qubit_levels: Sequence[tuple[float, float]],
    ) -> bool: ...
    def materialize(self) -> tuple[Any, ...]: ...
    def direct_weyl_flat(self, max_bytes: int) -> tuple[object, object, object]: ...
    def is_hermitian(self, tolerance: float) -> bool: ...
    def content_eq(self, other: "NativeHybridOperatorHandle") -> bool: ...
    def content_hash(self) -> int: ...

class NativeMajoranaOperatorHandle:
    @property
    def n_modes(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    def add(
        self, other: "NativeMajoranaOperatorHandle", max_bytes: int
    ) -> "NativeMajoranaOperatorHandle": ...
    def scale(
        self, scalar_re: float, scalar_im: float
    ) -> "NativeMajoranaOperatorHandle": ...
    def multiply(
        self, other: "NativeMajoranaOperatorHandle", max_bytes: int
    ) -> "NativeMajoranaOperatorHandle": ...
    def adjoint(self) -> "NativeMajoranaOperatorHandle": ...
    def commutator(
        self, other: "NativeMajoranaOperatorHandle", max_bytes: int
    ) -> "NativeMajoranaOperatorHandle": ...
    def anticommutator(
        self, other: "NativeMajoranaOperatorHandle", max_bytes: int
    ) -> "NativeMajoranaOperatorHandle": ...
    def materialize(
        self,
    ) -> tuple[int, object, object, object]: ...
    def to_fermion(self, max_bytes: int) -> "NativeFermionOperatorHandle": ...
    def is_hermitian(self, tolerance: float) -> bool: ...
    def content_eq(self, other: "NativeMajoranaOperatorHandle") -> bool: ...
    def content_hash(self) -> int: ...

class NativeMappingPlan:
    @property
    def n_modes(self) -> int: ...
    def encoding_flat(self) -> Sequence[int]: ...
    def inverse_encoding_flat(self) -> Sequence[int]: ...
    @property
    def cnot_operations(self) -> Sequence[tuple[int, int]]: ...
    @property
    def cnot_count(self) -> int: ...
    @property
    def estimated_bytes(self) -> int: ...
    def encode_occupation(self, occupation: Sequence[int]) -> Sequence[int]: ...
    def transform_pauli_handle(
        self,
        handle: "NativePauliOperatorHandle",
        max_bytes: int,
    ) -> "NativePauliOperatorHandle": ...
    def transform_pauli_handle_prefix(
        self,
        handle: "NativePauliOperatorHandle",
        prefix_length: int,
        max_bytes: int,
    ) -> "NativePauliOperatorHandle": ...
    def transform_majorana_handle(
        self,
        handle: "NativeMajoranaOperatorHandle",
        max_bytes: int,
    ) -> "NativePauliOperatorHandle": ...
    def transform_hybrid_handle(
        self,
        handle: "NativeHybridOperatorHandle",
        max_bytes: int,
    ) -> "NativeHybridOperatorHandle": ...

class NativeQwcGroupingHandle:
    def reconstruct(
        self, group_index: int, bitstrings: object
    ) -> tuple[int, int, object]: ...

def mapping_plan(mapping: str, n_modes: int, max_bytes: int) -> NativeMappingPlan: ...

class NativeChargeSectorPlan:
    @property
    def dimension(self) -> int: ...
    @property
    def estimated_bytes(self) -> int: ...
    def rank(self, occupations: Sequence[int]) -> int: ...
    def unrank(self, index: int) -> Sequence[int]: ...
    def basis_states(self, max_bytes: int) -> object: ...
    def compile_mvp(
        self,
        dimension: int,
        local_dimensions: Sequence[int],
        fermion_positions: Sequence[int],
        boson_positions: Sequence[int],
        qubit_positions: Sequence[int],
        qudit_positions: Sequence[int],
        fermion_creation: object,
        fermion_annihilation: object,
        boson_blocks: object,
        qubit_codes: object,
        mapped_present: Sequence[bool],
        mapped_codes: object,
        qudit_present: Sequence[bool],
        qudit_triples: object,
        coefficients: object,
        qudit_dimension: int,
        termwise_conserved: bool,
        max_bytes: int,
        fast_fermion_particles: int | None = ...,
    ) -> NativeChargeMvpPlan: ...
    def compile_mvp_pauli_handle(
        self,
        handle: NativePauliOperatorHandle,
        dimension: int,
        local_dimensions: Sequence[int],
        fermion_positions: Sequence[int],
        boson_positions: Sequence[int],
        qubit_positions: Sequence[int],
        qudit_positions: Sequence[int],
        termwise_conserved: bool,
        max_bytes: int,
        fast_fermion_particles: int | None = ...,
    ) -> NativeChargeMvpPlan: ...
    def compile_mvp_hybrid_handle(
        self,
        handle: NativeHybridOperatorHandle,
        dimension: int,
        local_dimensions: Sequence[int],
        fermion_positions: Sequence[int],
        boson_positions: Sequence[int],
        qubit_positions: Sequence[int],
        qudit_positions: Sequence[int],
        qudit_dimension: int,
        termwise_conserved: bool,
        max_bytes: int,
        fast_fermion_particles: int | None = ...,
    ) -> NativeChargeMvpPlan: ...

class NativeChargeMvpPlan:
    @property
    def dimension(self) -> int: ...
    @property
    def estimated_bytes(self) -> int: ...
    def apply(self, state: object, max_bytes: int) -> object: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...
    def compile_eager(self, max_bytes: int) -> NativeChargeEagerMvpPlan: ...

class NativeChargeEagerMvpPlan:
    @property
    def dimension(self) -> int: ...
    @property
    def transition_count(self) -> int: ...
    @property
    def estimated_bytes(self) -> int: ...
    def csr(self) -> tuple[object, object, object]: ...
    def coo(self, max_bytes: int) -> tuple[object, object, object]: ...
    def dense(self, max_bytes: int) -> object: ...
    def apply(self, state: object, max_bytes: int) -> object: ...
    def apply_with_parallelism(
        self, state: object, max_bytes: int, parallel: bool
    ) -> object: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...

def charge_sector_plan_compact(
    local_dimensions: Sequence[int],
    axis_kinds: Sequence[int],
    axis_indices: Sequence[int],
    fermion_weights: object,
    boson_weights: object,
    qubit_levels: object,
    target: Sequence[int],
    max_bytes: int,
) -> NativeChargeSectorPlan: ...
def pauli_analyze_charge_handle(
    handle: NativePauliOperatorHandle,
    qubit_levels: Sequence[tuple[float, float]],
    max_bytes: int,
) -> tuple[bool, int]: ...
def structured_dense_handle(
    handle: NativeHybridOperatorHandle,
    local_dimensions: Sequence[int],
    axes: Sequence[tuple[int, int]],
    max_bytes: int,
) -> tuple[int, object]: ...
def structured_sparse_handle(
    handle: NativeHybridOperatorHandle,
    local_dimensions: Sequence[int],
    axes: Sequence[tuple[int, int]],
    max_bytes: int,
) -> tuple[int, object, object, object]: ...
def structured_sparse_plan_handle(
    handle: NativeHybridOperatorHandle,
    local_dimensions: Sequence[int],
    axes: Sequence[tuple[int, int]],
    max_bytes: int,
) -> StructuredMvpPlan: ...
def structured_fermion_canonicalize(
    n_modes: int,
    factors: Sequence[Sequence[tuple[int, int]]],
    coefficients_re: Sequence[float],
    coefficients_im: Sequence[float],
    max_bytes: int,
) -> NativeFermionOperatorHandle: ...
def structured_boson_canonicalize(
    n_modes: int,
    factors: Sequence[Sequence[tuple[int, int]]],
    coefficients_re: Sequence[float],
    coefficients_im: Sequence[float],
    max_bytes: int,
) -> NativeBosonOperatorHandle: ...
def structured_hybrid_canonicalize(
    n_modes: int,
    n_bosons: int,
    nqubits: int,
    n_qudit_sites: int,
    qudit_dimension: int,
    input: object,
    max_bytes: int,
) -> NativeHybridOperatorHandle: ...
def structured_hybrid_jordan_wigner(
    n_modes: int,
    n_bosons: int,
    nqubits: int,
    n_qudit_sites: int,
    qudit_dimension: int,
    input: object,
    max_bytes: int,
) -> NativeHybridOperatorHandle: ...
def majorana_canonicalize(
    n_modes: int,
    indices: Sequence[Sequence[int]],
    coefficients_re: Sequence[float],
    coefficients_im: Sequence[float],
    max_bytes: int,
) -> NativeMajoranaOperatorHandle: ...

class NativeMvpPlan:
    @property
    def nqubits(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    @property
    def strategy(self) -> str: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...
    def apply(
        self,
        state: object,
        max_bytes: int,
    ) -> object: ...

class NativeZ2TaperingPlan:
    @property
    def nqubits_before(self) -> int: ...
    @property
    def nqubits_after(self) -> int: ...
    @property
    def generators(self) -> Sequence[Sequence[int]]: ...
    @property
    def sector(self) -> Sequence[int]: ...
    @property
    def removed_qubits(self) -> Sequence[int]: ...
    @property
    def clifford_operations(self) -> Sequence[tuple[int, int, int]]: ...
    def transform_operator_handle(
        self, operator: NativePauliOperatorHandle
    ) -> NativePauliOperatorHandle: ...

class NativeU1RestrictedOperator:
    @property
    def nqubits(self) -> int: ...
    @property
    def particle_number(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def apply(self, state: object, max_bytes: int) -> object: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...
    def mvp_plan(self, max_bytes: int) -> NativeU1MvpPlan: ...
    def dense(self, max_bytes: int) -> tuple[int, object]: ...
    def coo(self, max_bytes: int) -> tuple[int, object, object, object]: ...
    def csr(self, max_bytes: int) -> tuple[int, object, object, object]: ...

class NativeU1MvpPlan:
    @property
    def nqubits(self) -> int: ...
    @property
    def particle_number(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    @property
    def transition_count(self) -> int: ...
    def apply(self, state: object, max_bytes: int) -> object: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...

class NativeU1LazyMvpPlan:
    @property
    def nqubits(self) -> int: ...
    @property
    def particle_number(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    @property
    def estimated_bytes(self) -> int: ...
    def apply(self, state: object, max_bytes: int) -> object: ...
    def apply_into(self, state: object, output: object, max_bytes: int) -> None: ...

class NativeU1CircuitPlan:
    @property
    def nqubits(self) -> int: ...
    @property
    def particle_number(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    @property
    def nparameters(self) -> int: ...
    @property
    def gate_count(self) -> int: ...
    def run(self, initial_state: object, parameters: object) -> object: ...
    def run_cached(
        self, initial_state: object, parameters: object
    ) -> NativeU1FinalState: ...
    def probability(self, initial_state: object, parameters: object) -> object: ...
    def to_dense(self, initial_state: object, parameters: object) -> object: ...
    def probability_full(self, initial_state: object, parameters: object) -> object: ...
    def expectation(
        self,
        initial_state: object,
        structures: object,
        coefficients_re: object,
        coefficients_im: object,
        parameters: object,
    ) -> tuple[float, float]: ...
    def value_and_grad(
        self,
        initial_state: object,
        structures: object,
        coefficients_re: object,
        coefficients_im: object,
        parameters: object,
    ) -> tuple[float, object]: ...
    def expectation_handle(
        self,
        initial_state: object,
        observable: NativePauliOperatorHandle,
        parameters: object,
    ) -> tuple[float, float]: ...
    def value_and_grad_handle(
        self,
        initial_state: object,
        observable: NativePauliOperatorHandle,
        parameters: object,
    ) -> tuple[float, object]: ...

class NativeU1FinalState:
    def state_array(self) -> object: ...
    def probability(self) -> object: ...
    def to_dense(self) -> object: ...
    def probability_full(self) -> object: ...
    def expectation(
        self,
        structures: object,
        coefficients_re: object,
        coefficients_im: object,
    ) -> tuple[float, float]: ...
    def value_and_grad(
        self,
        structures: object,
        coefficients_re: object,
        coefficients_im: object,
    ) -> tuple[float, object]: ...
    def expectation_handle(
        self, observable: NativePauliOperatorHandle
    ) -> tuple[float, float]: ...
    def value_and_grad_handle(
        self, observable: NativePauliOperatorHandle
    ) -> tuple[float, object]: ...

class NativePropagationEngine:
    @property
    def nqubits(self) -> int: ...
    @property
    def nparameters(self) -> int: ...
    @property
    def gate_count(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    @property
    def max_weight(self) -> int | None: ...
    @property
    def is_exact(self) -> bool: ...
    @property
    def is_hermitian_observable(self) -> bool: ...
    def expectation(self, parameters: object) -> float: ...
    def value_and_grad(
        self, parameters: object, checkpoint_interval: int | None = None
    ) -> tuple[float, object]: ...
    def propagate_operator(self, parameters: object) -> NativePauliOperatorHandle: ...
    def profile(
        self, parameters: object
    ) -> tuple[float, int, int, int, int, Sequence[int], float]: ...

class NativeGateTape:
    @property
    def nqubits(self) -> int: ...
    @property
    def nparameters(self) -> int: ...
    @property
    def gate_count(self) -> int: ...

class NativePropagationBatch:
    @property
    def nqubits(self) -> int: ...
    @property
    def nparameters(self) -> int: ...
    @property
    def gate_count(self) -> int: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def max_weight(self) -> int | None: ...
    def expectations(self, parameters: object) -> object: ...
    def values_and_gradients(
        self, parameters: object, checkpoint_interval: int | None = None
    ) -> tuple[object, object]: ...

class NativeSPPSEngine:
    @property
    def nqubits(self) -> int: ...
    @property
    def nparameters(self) -> int: ...
    @property
    def gate_count(self) -> int: ...
    @property
    def observable_terms(self) -> int: ...
    @property
    def smoothing(self) -> float: ...
    def expectation(
        self, parameters: object, samples_per_term: int, seed: int
    ) -> tuple[float, float, int, Sequence[int], int, int]: ...
    def value_and_grad(
        self, parameters: object, samples_per_term: int, seed: int
    ) -> tuple[
        float,
        object,
        float,
        int,
        Sequence[int],
        int,
        int,
        float | None,
        Sequence[float] | None,
        bool | None,
    ]: ...
    def value_and_grad_adaptive(
        self,
        parameters: object,
        initial_samples_per_term: int,
        max_samples_per_term: int,
        gradient_tolerance: float,
        seed: int,
    ) -> tuple[
        float,
        object,
        float,
        int,
        Sequence[int],
        int,
        int,
        float | None,
        Sequence[float] | None,
        bool | None,
    ]: ...

def pauli_weight(
    nqubits: int, x_words: Sequence[int], z_words: Sequence[int]
) -> int: ...
def pauli_support(
    nqubits: int, x_words: Sequence[int], z_words: Sequence[int]
) -> Sequence[int]: ...
def pauli_codes(
    nqubits: int, x_words: Sequence[int], z_words: Sequence[int]
) -> Sequence[int]: ...
def pauli_from_codes(
    nqubits: int, codes: Sequence[int]
) -> tuple[Sequence[int], Sequence[int]]: ...
def pauli_batch_from_codes(
    nqubits: int, structures: Sequence[Sequence[int]]
) -> tuple[int, Sequence[int], Sequence[int]]: ...
def pauli_multiply(
    nqubits: int,
    x_words_left: Sequence[int],
    z_words_left: Sequence[int],
    x_words_right: Sequence[int],
    z_words_right: Sequence[int],
) -> tuple[Sequence[int], Sequence[int], int]: ...
def pauli_symplectic_inner_product(
    nqubits: int,
    x_words_left: Sequence[int],
    z_words_left: Sequence[int],
    x_words_right: Sequence[int],
    z_words_right: Sequence[int],
) -> int: ...
def pauli_canonicalize_batch(
    nqubits: int,
    structures: Sequence[Sequence[int]],
    coefficients_re: Sequence[float],
    coefficients_im: Sequence[float],
) -> tuple[
    Sequence[Sequence[int]],
    Sequence[float],
    Sequence[float],
    Sequence[int],
    Sequence[int],
]: ...
def pauli_canonicalize_batch_array(
    nqubits: int,
    structures: object,
    coefficients: object,
) -> tuple[
    Sequence[Sequence[int]],
    Sequence[float],
    Sequence[float],
    Sequence[int],
    Sequence[int],
]: ...
def pauli_canonicalize_batch_numpy(
    nqubits: int,
    structures: object,
    coefficients: object,
) -> tuple[int, object, object, object, object]: ...
def pauli_operator_native(
    nqubits: int,
    structures: Sequence[Sequence[int]],
    coefficients_re: Sequence[float],
    coefficients_im: Sequence[float],
    max_bytes: int,
) -> NativePauliOperatorHandle: ...
def pauli_operator_native_array(
    nqubits: int, structures: object, coefficients: object, max_bytes: int
) -> NativePauliOperatorHandle: ...
def pauli_group_handle(
    handle: NativePauliOperatorHandle,
    mode: int,
    algorithm: int,
    max_entries: int,
) -> tuple[
    Sequence[Sequence[int]], Sequence[Sequence[int]], Sequence[Sequence[Sequence[int]]]
]: ...
def pauli_qwc_group_handle(
    handle: NativePauliOperatorHandle,
    algorithm: int,
    max_entries: int,
) -> tuple[
    Sequence[Sequence[int]],
    Sequence[Sequence[int]],
    Sequence[Sequence[Sequence[int]]],
    NativeQwcGroupingHandle,
]: ...
def pauli_compatibility_matrix_handle(
    handle: NativePauliOperatorHandle, mode: int, max_entries: int
) -> Sequence[bool]: ...
def pauli_incompatibility_edges_handle(
    handle: NativePauliOperatorHandle, mode: int, max_edges: int
) -> Sequence[tuple[int, int]]: ...
def pauli_dense_handle(
    handle: NativePauliOperatorHandle, max_bytes: int
) -> tuple[int, object]: ...
def pauli_coo_handle(
    handle: NativePauliOperatorHandle, max_bytes: int
) -> tuple[int, object, object, object]: ...
def pauli_csr_handle(
    handle: NativePauliOperatorHandle, max_bytes: int
) -> tuple[int, object, object, object]: ...
def pauli_mvp_handle(
    handle: NativePauliOperatorHandle, state: object, max_bytes: int
) -> object: ...
def pauli_mvp_plan_handle(
    handle: NativePauliOperatorHandle,
    max_bytes: int,
    storage: str = ...,
) -> NativeMvpPlan: ...
def pauli_backend_plan_handle(
    handle: NativePauliOperatorHandle, max_bytes: int
) -> tuple[int, int, int, Sequence[int], Sequence[int], Sequence[complex]]: ...
def pauli_commutes(
    nqubits: int,
    x_words_left: Sequence[int],
    z_words_left: Sequence[int],
    x_words_right: Sequence[int],
    z_words_right: Sequence[int],
) -> bool: ...
def pauli_find_z2_symmetries_handle(
    operator: NativePauliOperatorHandle, max_bytes: int
) -> tuple[Sequence[Sequence[int]], int]: ...
def pauli_z2_tapering_plan(
    nqubits: int,
    generators: Sequence[Sequence[int]],
    sector: Sequence[int],
) -> NativeZ2TaperingPlan: ...
def pauli_restrict_u1_handle(
    handle: NativePauliOperatorHandle, particle_number: int, max_bytes: int
) -> NativeU1RestrictedOperator: ...
def pauli_restrict_u1_lazy_handle(
    handle: NativePauliOperatorHandle, particle_number: int, max_bytes: int
) -> NativeU1LazyMvpPlan: ...
def u1_basis_words(
    nqubits: int,
    particle_number: int,
    max_bytes: int,
) -> tuple[int, int, object]: ...
def u1_circuit_plan(
    nqubits: int,
    particle_number: int,
    schema_version: int,
    nparameters: int,
    angles: object,
    gates: object,
    max_bytes: int,
) -> NativeU1CircuitPlan: ...
def pauli_gate_tape(
    nqubits: int,
    operations: Sequence[tuple[int, int, int, int, float, Sequence[float]]],
    max_bytes: int | None = None,
) -> NativeGateTape: ...
def pauli_propagation_engine_tape(
    tape: NativeGateTape,
    observable: NativePauliOperatorHandle,
    state_kind: int,
    state_bits: Sequence[int],
    state_values: Sequence[float],
    max_weight: int | None = None,
    max_bytes: int | None = None,
) -> NativePropagationEngine: ...
def pauli_propagation_batch_handles_tape(
    tape: NativeGateTape,
    observables: Sequence[NativePauliOperatorHandle],
    state_kind: int,
    state_bits: Sequence[int],
    state_values: Sequence[float],
    max_weight: int | None = None,
    max_bytes: int | None = None,
) -> NativePropagationBatch: ...
def pauli_spps_engine_tape(
    tape: NativeGateTape,
    observable: NativePauliOperatorHandle,
    state_kind: int,
    state_bits: Sequence[int],
    state_values: Sequence[float],
    smoothing: float = 0.01,
    max_bytes: int | None = None,
) -> NativeSPPSEngine: ...
