//! Pure Rust Pauli algebra and deterministic structural utilities.

use std::cmp::Ordering;
use std::collections::BTreeMap;
use std::fmt;
use std::mem::size_of;
use std::ops::{Add, AddAssign, Mul, MulAssign, Neg, Sub, SubAssign};

use rayon::prelude::*;

/// A small dependency-free complex number used by the native numeric path.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Complex64 {
    /// Real component.
    pub re: f64,
    /// Imaginary component.
    pub im: f64,
}

impl Complex64 {
    /// Construct a complex number from its components.
    pub const fn new(re: f64, im: f64) -> Self {
        Self { re, im }
    }

    /// Return the complex conjugate.
    pub const fn conj(self) -> Self {
        Self::new(self.re, -self.im)
    }

    /// Return the squared magnitude.
    pub fn norm_sqr(self) -> f64 {
        self.re.mul_add(self.re, self.im * self.im)
    }

    /// Return whether both components are exactly zero.
    pub fn is_zero(self) -> bool {
        self.re == 0.0 && self.im == 0.0
    }
}

impl Add for Complex64 {
    type Output = Self;

    fn add(self, rhs: Self) -> Self::Output {
        Self::new(self.re + rhs.re, self.im + rhs.im)
    }
}

impl AddAssign for Complex64 {
    fn add_assign(&mut self, rhs: Self) {
        *self = *self + rhs;
    }
}

impl Sub for Complex64 {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self::Output {
        Self::new(self.re - rhs.re, self.im - rhs.im)
    }
}

impl SubAssign for Complex64 {
    fn sub_assign(&mut self, rhs: Self) {
        *self = *self - rhs;
    }
}

impl Mul for Complex64 {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self::Output {
        Self::new(
            self.re.mul_add(rhs.re, -(self.im * rhs.im)),
            self.re.mul_add(rhs.im, self.im * rhs.re),
        )
    }
}

impl Mul<f64> for Complex64 {
    type Output = Self;

    fn mul(self, rhs: f64) -> Self::Output {
        Self::new(self.re * rhs, self.im * rhs)
    }
}

impl MulAssign for Complex64 {
    fn mul_assign(&mut self, rhs: Self) {
        *self = *self * rhs;
    }
}

impl MulAssign<f64> for Complex64 {
    fn mul_assign(&mut self, rhs: f64) {
        *self = *self * rhs;
    }
}

impl Neg for Complex64 {
    type Output = Self;

    fn neg(self) -> Self::Output {
        Self::new(-self.re, -self.im)
    }
}

/// Typed errors shared by the Rust core and the Python exception mapping.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PauliError {
    /// A code was not one of I/X/Y/Z.
    InvalidCode { code: u8, index: usize },
    /// Packed arrays do not have the required number of words.
    InvalidWordLength { expected: usize, actual: usize },
    /// Two operands use different qubit counts.
    IncompatibleQubitCounts { left: usize, right: usize },
    /// A structure has the wrong number of sites.
    InvalidStructureLength { expected: usize, actual: usize },
    /// A non-finite coefficient was supplied.
    NonFiniteCoefficient { index: usize },
    /// A requested dimension cannot be represented or allocated.
    Overflow { context: &'static str },
    /// A requested allocation exceeds an explicit limit.
    MemoryLimit { requested: u128, limit: u128 },
}

impl fmt::Display for PauliError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidCode { code, index } => {
                write!(
                    formatter,
                    "invalid Pauli code {code} at index {index}; expected 0..3"
                )
            }
            Self::InvalidWordLength { expected, actual } => {
                write!(formatter, "expected {expected} packed words, got {actual}")
            }
            Self::IncompatibleQubitCounts { left, right } => {
                write!(formatter, "incompatible qubit counts: {left} and {right}")
            }
            Self::InvalidStructureLength { expected, actual } => {
                write!(
                    formatter,
                    "expected structure length {expected}, got {actual}"
                )
            }
            Self::NonFiniteCoefficient { index } => {
                write!(formatter, "coefficient at index {index} is not finite")
            }
            Self::Overflow { context } => write!(formatter, "integer overflow while {context}"),
            Self::MemoryLimit { requested, limit } => {
                write!(
                    formatter,
                    "requested {requested} bytes exceeds memory limit {limit}"
                )
            }
        }
    }
}

impl std::error::Error for PauliError {}

/// The exact phase generated by multiplying two Hermitian Pauli words.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PauliPhase {
    /// `+1`.
    PlusOne,
    /// `+i`.
    PlusI,
    /// `-1`.
    MinusOne,
    /// `-i`.
    MinusI,
}

impl PauliPhase {
    /// Return the phase as a complex128-compatible value.
    pub const fn as_complex(self) -> Complex64 {
        match self {
            Self::PlusOne => Complex64::new(1.0, 0.0),
            Self::PlusI => Complex64::new(0.0, 1.0),
            Self::MinusOne => Complex64::new(-1.0, 0.0),
            Self::MinusI => Complex64::new(0.0, -1.0),
        }
    }

    fn exponent(self) -> u8 {
        match self {
            Self::PlusOne => 0,
            Self::PlusI => 1,
            Self::MinusOne => 2,
            Self::MinusI => 3,
        }
    }

    fn from_exponent(exponent: u8) -> Self {
        match exponent % 4 {
            0 => Self::PlusOne,
            1 => Self::PlusI,
            2 => Self::MinusOne,
            _ => Self::MinusI,
        }
    }

    fn multiply(self, rhs: Self) -> Self {
        Self::from_exponent(self.exponent() + rhs.exponent())
    }
}

/// A phase-free Pauli word in binary symplectic representation.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct PauliWord {
    nqubits: usize,
    x_words: Vec<u64>,
    z_words: Vec<u64>,
}

impl PauliWord {
    /// Build and canonicalize a word from packed little-endian masks.
    pub fn from_words(
        nqubits: usize,
        mut x_words: Vec<u64>,
        mut z_words: Vec<u64>,
    ) -> Result<Self, PauliError> {
        let expected = packed_word_count(nqubits);
        if x_words.len() != expected {
            return Err(PauliError::InvalidWordLength {
                expected,
                actual: x_words.len(),
            });
        }
        if z_words.len() != expected {
            return Err(PauliError::InvalidWordLength {
                expected,
                actual: z_words.len(),
            });
        }
        if let Some(mask) = final_word_mask(nqubits) {
            let last = expected - 1;
            x_words[last] &= mask;
            z_words[last] &= mask;
        }
        Ok(Self {
            nqubits,
            x_words,
            z_words,
        })
    }

    /// Build a word from external I/X/Y/Z codes.
    pub fn from_codes(nqubits: usize, codes: &[u8]) -> Result<Self, PauliError> {
        if codes.len() != nqubits {
            return Err(PauliError::InvalidStructureLength {
                expected: nqubits,
                actual: codes.len(),
            });
        }
        let word_count = packed_word_count(nqubits);
        let mut x_words = vec![0; word_count];
        let mut z_words = vec![0; word_count];
        for (qubit, &code) in codes.iter().enumerate() {
            let (x, z) = code_bits(code, qubit)?;
            x_words[qubit / 64] |= x << (qubit % 64);
            z_words[qubit / 64] |= z << (qubit % 64);
        }
        Self::from_words(nqubits, x_words, z_words)
    }

    /// Return the number of qubits represented by the word.
    pub fn nqubits(&self) -> usize {
        self.nqubits
    }

    /// Return the packed X masks.
    pub fn x_words(&self) -> &[u64] {
        &self.x_words
    }

    /// Return the packed Z masks.
    pub fn z_words(&self) -> &[u64] {
        &self.z_words
    }

    /// Convert to external I/X/Y/Z codes in qubit order.
    pub fn codes(&self) -> Vec<u8> {
        (0..self.nqubits)
            .map(|qubit| {
                let x = (self.x_words[qubit / 64] >> (qubit % 64)) & 1;
                let z = (self.z_words[qubit / 64] >> (qubit % 64)) & 1;
                match (x, z) {
                    (0, 0) => 0,
                    (1, 0) => 1,
                    (1, 1) => 2,
                    (0, 1) => 3,
                    _ => unreachable!("packed symplectic bits are binary"),
                }
            })
            .collect()
    }

    /// Return the non-identity qubit indices.
    pub fn support(&self) -> Vec<usize> {
        self.codes()
            .into_iter()
            .enumerate()
            .filter_map(|(index, code)| (code != 0).then_some(index))
            .collect()
    }

    /// Return the number of non-identity sites.
    pub fn weight(&self) -> u32 {
        self.x_words
            .iter()
            .zip(&self.z_words)
            .map(|(x_word, z_word)| (x_word | z_word).count_ones())
            .sum()
    }

    /// Return the binary symplectic inner product.
    pub fn symplectic_inner_product(&self, other: &Self) -> Result<u8, PauliError> {
        self.ensure_compatible(other)?;
        let parity = self
            .x_words
            .iter()
            .zip(&self.z_words)
            .zip(&other.x_words)
            .zip(&other.z_words)
            .fold(
                0_u32,
                |accumulator, (((x_left, z_left), x_right), z_right)| {
                    accumulator
                        ^ ((x_left & z_right).count_ones() & 1)
                        ^ ((z_left & x_right).count_ones() & 1)
                },
            );
        Ok((parity & 1) as u8)
    }

    /// Return whether this word commutes with `other`.
    pub fn commutes_with(&self, other: &Self) -> Result<bool, PauliError> {
        Ok(self.symplectic_inner_product(other)? == 0)
    }

    /// Return whether words are compatible for one local measurement basis.
    pub fn qwc_compatible(&self, other: &Self) -> Result<bool, PauliError> {
        self.ensure_compatible(other)?;
        Ok(self
            .codes()
            .into_iter()
            .zip(other.codes())
            .all(|(left, right)| left == 0 || right == 0 || left == right))
    }

    /// Multiply two phase-free words and return the exact discrete phase.
    pub fn multiply(&self, other: &Self) -> Result<(Self, PauliPhase), PauliError> {
        self.ensure_compatible(other)?;
        let result = Self::from_words(
            self.nqubits,
            self.x_words
                .iter()
                .zip(&other.x_words)
                .map(|(left, right)| left ^ right)
                .collect(),
            self.z_words
                .iter()
                .zip(&other.z_words)
                .map(|(left, right)| left ^ right)
                .collect(),
        )?;
        let mut phase = PauliPhase::PlusOne;
        for (left, right) in self.codes().into_iter().zip(other.codes()) {
            phase = phase.multiply(local_product(left, right).1);
        }
        Ok((result, phase))
    }

    /// Return the adjoint word. Phase-free Pauli basis words are Hermitian.
    pub fn adjoint(&self) -> Self {
        self.clone()
    }

    fn ensure_compatible(&self, other: &Self) -> Result<(), PauliError> {
        if self.nqubits != other.nqubits {
            return Err(PauliError::IncompatibleQubitCounts {
                left: self.nqubits,
                right: other.nqubits,
            });
        }
        Ok(())
    }
}

impl Ord for PauliWord {
    fn cmp(&self, other: &Self) -> Ordering {
        self.nqubits
            .cmp(&other.nqubits)
            .then_with(|| self.codes().cmp(&other.codes()))
    }
}

impl PartialOrd for PauliWord {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// A coefficient-bearing canonical Pauli term.
#[derive(Clone, Debug, PartialEq)]
pub struct PauliTerm {
    /// Phase-free Pauli structure.
    pub word: PauliWord,
    /// Complex128-compatible coefficient.
    pub coefficient: Complex64,
}

/// Result of deterministic batch canonicalization before static zero removal.
pub struct Canonicalization {
    /// Canonical keys and their aggregated coefficients, including exact zeros.
    pub terms: Vec<PauliTerm>,
    /// Input-term index to canonical-key index mapping.
    pub input_to_canonical: Vec<usize>,
    /// Exact phase carried by each phase-free code-array input term.
    pub phase_multipliers: Vec<PauliPhase>,
}

#[derive(Clone, Copy, Debug)]
struct MatrixTerm {
    x_mask: usize,
    z_mask: usize,
    weighted_phase: Complex64,
}

#[derive(Clone, Copy, Debug, Default)]
struct SparseEntry {
    column: u64,
    value: Complex64,
}

struct SparseEntries {
    entries: Vec<SparseEntry>,
    row_counts: Vec<usize>,
}

#[derive(Debug)]
struct MatrixGroup {
    x_mask: usize,
    terms: Vec<MatrixTerm>,
}

#[derive(Clone, Debug)]
struct MvpGroup {
    x_mask: usize,
    diagonal: Vec<Complex64>,
}

/// Strategy selected for a reusable matrix-free MVP plan.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MvpStrategy {
    /// Store one precomputed diagonal for every distinct X permutation mask.
    XMaskDiagonal,
    /// Evaluate every canonical Pauli term directly during application.
    TermDirect,
}

/// A reusable, phase-precomputed CPU matrix-free Pauli application plan.
#[derive(Clone, Debug)]
pub struct MvpPlan {
    nqubits: usize,
    term_count: usize,
    terms: Option<Vec<MatrixTerm>>,
    diagonal_groups: Option<Vec<MvpGroup>>,
    strategy: MvpStrategy,
}

impl MvpPlan {
    /// Compile matrix masks and fixed Y phases from a canonical operator.
    pub fn from_operator(operator: &PauliOperator) -> Result<Self, PauliError> {
        let terms = operator
            .terms
            .iter()
            .map(matrix_term)
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Self {
            nqubits: operator.nqubits,
            term_count: terms.len(),
            terms: Some(terms),
            diagonal_groups: None,
            strategy: MvpStrategy::TermDirect,
        })
    }

    /// Compile a reusable plan with one precomputed diagonal per X mask.
    pub fn from_operator_reusable(
        operator: &PauliOperator,
        max_bytes: u128,
    ) -> Result<Self, PauliError> {
        let direct = Self::from_operator(operator)?;
        let dimension = matrix_dimension(operator.nqubits)?;
        let groups = group_matrix_terms(direct.terms.as_ref().expect("direct terms").clone());
        let diagonal_bytes = groups
            .len()
            .checked_mul(dimension)
            .and_then(|count| count.checked_mul(size_of::<Complex64>()))
            .ok_or(PauliError::Overflow {
                context: "estimating reusable MVP plan memory",
            })?;
        let term_bytes = direct
            .terms
            .as_ref()
            .expect("direct terms")
            .len()
            .checked_mul(size_of::<MatrixTerm>())
            .ok_or(PauliError::Overflow {
                context: "estimating reusable MVP term memory",
            })?;
        check_allocation(term_bytes as u128, max_bytes)?;
        if diagonal_bytes as u128 > max_bytes - term_bytes as u128 {
            return Ok(direct);
        }
        let diagonal_groups = groups
            .into_par_iter()
            .map(|group| {
                let mut diagonal = vec![Complex64::default(); dimension];
                for (column, value) in diagonal.iter_mut().enumerate() {
                    for term in &group.terms {
                        let mut contribution = term.weighted_phase;
                        if (term.z_mask & column).count_ones() & 1 != 0 {
                            contribution = -contribution;
                        }
                        *value += contribution;
                    }
                }
                MvpGroup {
                    x_mask: group.x_mask,
                    diagonal,
                }
            })
            .collect();
        Ok(Self {
            nqubits: direct.nqubits,
            term_count: direct.term_count,
            terms: None,
            diagonal_groups: Some(diagonal_groups),
            strategy: MvpStrategy::XMaskDiagonal,
        })
    }

    /// Return the number of qubits in this plan.
    pub fn nqubits(&self) -> usize {
        self.nqubits
    }

    /// Return the number of canonical matrix terms in this plan.
    pub fn term_count(&self) -> usize {
        self.term_count
    }

    /// Return the selected application strategy as a stable label.
    pub fn strategy(&self) -> MvpStrategy {
        self.strategy
    }

    /// Apply the plan without materializing a matrix.
    pub fn apply(
        &self,
        state: &[Complex64],
        max_bytes: u128,
    ) -> Result<Vec<Complex64>, PauliError> {
        let dimension = matrix_dimension(self.nqubits)?;
        let mut result = vec![Complex64::default(); dimension];
        self.apply_into(state, &mut result, max_bytes)?;
        Ok(result)
    }

    /// Apply the plan into caller-owned storage without allocating a result.
    pub fn apply_into(
        &self,
        state: &[Complex64],
        result: &mut [Complex64],
        max_bytes: u128,
    ) -> Result<(), PauliError> {
        let dimension = matrix_dimension(self.nqubits)?;
        if state.len() != dimension {
            return Err(PauliError::InvalidStructureLength {
                expected: dimension,
                actual: state.len(),
            });
        }
        if result.len() != dimension {
            return Err(PauliError::InvalidStructureLength {
                expected: dimension,
                actual: result.len(),
            });
        }
        check_allocation(
            dimension as u128 * size_of::<Complex64>() as u128,
            max_bytes,
        )?;
        let work = self
            .diagonal_groups
            .as_ref()
            .map_or(self.term_count, Vec::len)
            .saturating_mul(dimension);
        if work >= 1 << 16 {
            result.par_iter_mut().enumerate().for_each(|(row, output)| {
                let mut value = Complex64::default();
                if let Some(groups) = &self.diagonal_groups {
                    for group in groups {
                        value += group.diagonal[row ^ group.x_mask] * state[row ^ group.x_mask];
                    }
                } else {
                    for term in self.terms.as_ref().expect("direct terms") {
                        let column = row ^ term.x_mask;
                        let contribution = term.weighted_phase * state[column];
                        if (term.z_mask & column).count_ones() & 1 == 0 {
                            value += contribution;
                        } else {
                            value -= contribution;
                        }
                    }
                }
                *output = value;
            });
        } else {
            for (row, output) in result.iter_mut().enumerate() {
                if let Some(groups) = &self.diagonal_groups {
                    for group in groups {
                        let column = row ^ group.x_mask;
                        *output += group.diagonal[column] * state[column];
                    }
                } else {
                    for term in self.terms.as_ref().expect("direct terms") {
                        let column = row ^ term.x_mask;
                        let contribution = term.weighted_phase * state[column];
                        if (term.z_mask & column).count_ones() & 1 == 0 {
                            *output += contribution;
                        } else {
                            *output -= contribution;
                        }
                    }
                }
            }
        }
        Ok(())
    }
}

/// A deterministic, canonical Pauli operator.
#[derive(Clone, Debug, PartialEq)]
pub struct PauliOperator {
    nqubits: usize,
    terms: Vec<PauliTerm>,
}

/// Deterministic sparse COO output from the Rust core.
pub struct CooMatrix {
    /// Matrix dimension.
    pub dimension: usize,
    /// Row indices in row-major order.
    pub rows: Vec<u64>,
    /// Column indices in row-major order.
    pub columns: Vec<u64>,
    /// Complex128-compatible values.
    pub values: Vec<Complex64>,
}

/// Deterministic sparse CSR output from the Rust core.
pub struct CsrMatrix {
    /// Matrix dimension.
    pub dimension: usize,
    /// Row pointer array.
    pub indptr: Vec<u64>,
    /// Column indices.
    pub columns: Vec<u64>,
    /// Complex128-compatible values.
    pub values: Vec<Complex64>,
}

/// Pure-array backend MVP plan data.
pub struct BackendMvpPlan {
    /// Qubit count.
    pub nqubits: usize,
    /// Packed words per term.
    pub word_count: usize,
    /// Flat X masks.
    pub x_words: Vec<u64>,
    /// Flat Z masks.
    pub z_words: Vec<u64>,
    /// Coefficients in canonical term order.
    pub coefficients: Vec<Complex64>,
}

/// Compatibility relation used by deterministic measurement grouping.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GroupingMode {
    /// Qubit-wise commuting: every local pair is equal or contains identity.
    QubitWise,
    /// Algebraic commuting: the binary symplectic inner product is zero.
    General,
}

/// Deterministic graph-coloring strategy.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GroupingAlgorithm {
    /// Order vertices by descending incompatibility degree.
    LargestFirst,
    /// Repeatedly choose the highest saturation-degree vertex.
    Dsatur,
}

/// Return a deterministic partition of input term indices into compatible groups.
pub fn group_words(
    words: &[PauliWord],
    mode: GroupingMode,
    algorithm: GroupingAlgorithm,
) -> Result<Vec<Vec<usize>>, PauliError> {
    if let Some(first) = words.first() {
        if let Some(other) = words.iter().find(|word| word.nqubits != first.nqubits) {
            return Err(PauliError::IncompatibleQubitCounts {
                left: first.nqubits,
                right: other.nqubits,
            });
        }
    }
    let size = words.len();
    let mut incompatible = vec![vec![false; size]; size];
    for left in 0..size {
        for right in (left + 1)..size {
            let compatible = match mode {
                GroupingMode::QubitWise => words[left].qwc_compatible(&words[right])?,
                GroupingMode::General => words[left].commutes_with(&words[right])?,
            };
            incompatible[left][right] = !compatible;
            incompatible[right][left] = !compatible;
        }
    }
    let mut groups: Vec<Vec<usize>> = Vec::new();
    if algorithm == GroupingAlgorithm::LargestFirst {
        let mut order: Vec<usize> = (0..size).collect();
        order.sort_by(|left, right| {
            degree(*right, &incompatible)
                .cmp(&degree(*left, &incompatible))
                .then_with(|| left.cmp(right))
        });
        for vertex in order {
            place_vertex(vertex, &incompatible, &mut groups);
        }
    } else {
        let mut colors = vec![None; size];
        for _ in 0..size {
            let vertex = (0..size)
                .filter(|index| colors[*index].is_none())
                .max_by(|left, right| {
                    saturation(*left, &incompatible, &colors)
                        .cmp(&saturation(*right, &incompatible, &colors))
                        .then_with(|| {
                            degree(*left, &incompatible).cmp(&degree(*right, &incompatible))
                        })
                        .then_with(|| right.cmp(left))
                })
                .expect("uncolored vertex exists for every DSATUR iteration");
            let mut color = 0;
            while colors
                .iter()
                .enumerate()
                .any(|(index, current)| *current == Some(color) && incompatible[vertex][index])
            {
                color += 1;
            }
            colors[vertex] = Some(color);
        }
        let max_color = colors.iter().flatten().copied().max().unwrap_or(0);
        groups = (0..=max_color).map(|_| Vec::new()).collect();
        for (vertex, color) in colors.into_iter().enumerate() {
            groups[color.expect("all DSATUR vertices are colored")].push(vertex);
        }
        groups.retain(|group| !group.is_empty());
    }
    for group in &mut groups {
        group.sort_unstable();
    }
    groups.sort_by_key(|group| group[0]);
    Ok(groups)
}

/// Build a bounded dense compatibility matrix for a batch of words.
pub fn compatibility_matrix(
    words: &[PauliWord],
    mode: GroupingMode,
    max_entries: usize,
) -> Result<Vec<bool>, PauliError> {
    let entries = words
        .len()
        .checked_mul(words.len())
        .ok_or(PauliError::Overflow {
            context: "estimating compatibility matrix entries",
        })?;
    if entries > max_entries {
        return Err(PauliError::MemoryLimit {
            requested: entries as u128,
            limit: max_entries as u128,
        });
    }
    let mut matrix = vec![false; entries];
    for left in 0..words.len() {
        for right in 0..words.len() {
            matrix[left * words.len() + right] = match mode {
                GroupingMode::QubitWise => words[left].qwc_compatible(&words[right])?,
                GroupingMode::General => words[left].commutes_with(&words[right])?,
            };
        }
    }
    Ok(matrix)
}

/// Build a bounded streaming incompatibility edge list without materializing
/// the dense matrix.
pub fn incompatibility_edges(
    words: &[PauliWord],
    mode: GroupingMode,
    max_edges: usize,
) -> Result<Vec<(usize, usize)>, PauliError> {
    let mut edges = Vec::new();
    for left in 0..words.len() {
        for right in (left + 1)..words.len() {
            let compatible = match mode {
                GroupingMode::QubitWise => words[left].qwc_compatible(&words[right])?,
                GroupingMode::General => words[left].commutes_with(&words[right])?,
            };
            if !compatible {
                if edges.len() >= max_edges {
                    return Err(PauliError::MemoryLimit {
                        requested: (edges.len() + 1) as u128,
                        limit: max_edges as u128,
                    });
                }
                edges.push((left, right));
            }
        }
    }
    Ok(edges)
}

fn degree(vertex: usize, incompatible: &[Vec<bool>]) -> usize {
    incompatible[vertex].iter().filter(|value| **value).count()
}

fn place_vertex(vertex: usize, incompatible: &[Vec<bool>], groups: &mut Vec<Vec<usize>>) {
    if let Some(group) = groups
        .iter_mut()
        .find(|group| group.iter().all(|other| !incompatible[vertex][*other]))
    {
        group.push(vertex);
    } else {
        groups.push(vec![vertex]);
    }
}

fn saturation(vertex: usize, incompatible: &[Vec<bool>], colors: &[Option<usize>]) -> usize {
    let mut seen = Vec::new();
    for (other, is_incompatible) in incompatible[vertex].iter().enumerate() {
        if *is_incompatible {
            if let Some(color) = colors[other] {
                if !seen.contains(&color) {
                    seen.push(color);
                }
            }
        }
    }
    seen.len()
}

fn canonicalize(
    nqubits: usize,
    structures: &[Vec<u8>],
    coefficients: &[Complex64],
) -> Result<Canonicalization, PauliError> {
    if structures.len() != coefficients.len() {
        return Err(PauliError::InvalidStructureLength {
            expected: structures.len(),
            actual: coefficients.len(),
        });
    }
    let mut aggregate = BTreeMap::<PauliWord, Vec<(usize, Complex64)>>::new();
    for (index, (structure, &coefficient)) in structures.iter().zip(coefficients).enumerate() {
        if !coefficient.re.is_finite() || !coefficient.im.is_finite() {
            return Err(PauliError::NonFiniteCoefficient { index });
        }
        let word = PauliWord::from_codes(nqubits, structure)?;
        aggregate
            .entry(word)
            .or_default()
            .push((index, coefficient));
    }
    let mut terms = Vec::with_capacity(aggregate.len());
    let mut input_to_canonical = vec![0_usize; structures.len()];
    for (canonical_index, (word, mut contributions)) in aggregate.into_iter().enumerate() {
        for (input_index, _) in &contributions {
            input_to_canonical[*input_index] = canonical_index;
        }
        // Sort duplicate contributions by their IEEE bit patterns so
        // aggregation is independent of input order while retaining the
        // exact-zero policy. Input indices are a final deterministic tie-break.
        contributions
            .sort_by_key(|(index, value)| (value.re.to_bits(), value.im.to_bits(), *index));
        let coefficient = contributions
            .into_iter()
            .map(|(_, value)| value)
            .fold(Complex64::default(), |sum, value| sum + value);
        terms.push(PauliTerm { word, coefficient });
    }
    Ok(Canonicalization {
        terms,
        input_to_canonical,
        phase_multipliers: vec![PauliPhase::PlusOne; structures.len()],
    })
}

impl PauliOperator {
    /// Construct an operator, aggregate duplicate words, sort by code tuple,
    /// and remove only exact-zero coefficients.
    pub fn from_terms(
        nqubits: usize,
        structures: &[Vec<u8>],
        coefficients: &[Complex64],
    ) -> Result<Self, PauliError> {
        if structures.len() != coefficients.len() {
            return Err(PauliError::InvalidStructureLength {
                expected: structures.len(),
                actual: coefficients.len(),
            });
        }
        let mut aggregate = BTreeMap::<PauliWord, Vec<Complex64>>::new();
        for (index, (structure, &coefficient)) in structures.iter().zip(coefficients).enumerate() {
            if !coefficient.re.is_finite() || !coefficient.im.is_finite() {
                return Err(PauliError::NonFiniteCoefficient { index });
            }
            let word = PauliWord::from_codes(nqubits, structure)?;
            aggregate.entry(word).or_default().push(coefficient);
        }
        let terms = aggregate
            .into_iter()
            .filter_map(|(word, mut values)| {
                // Sort duplicate contributions by their IEEE bit patterns so
                // aggregation is independent of input order while retaining
                // the exact-zero policy.
                values.sort_by_key(|value| (value.re.to_bits(), value.im.to_bits()));
                let coefficient = values
                    .into_iter()
                    .fold(Complex64::default(), |sum, value| sum + value);
                (!coefficient.is_zero()).then_some(PauliTerm { word, coefficient })
            })
            .collect();
        Ok(Self { nqubits, terms })
    }

    /// Canonicalize a batch while retaining input mapping and exact zeros.
    pub fn canonicalize(
        nqubits: usize,
        structures: &[Vec<u8>],
        coefficients: &[Complex64],
    ) -> Result<Canonicalization, PauliError> {
        canonicalize(nqubits, structures, coefficients)
    }

    /// Construct an empty operator on `nqubits`.
    pub fn empty(nqubits: usize) -> Self {
        Self {
            nqubits,
            terms: Vec::new(),
        }
    }

    /// Return the qubit count.
    pub fn nqubits(&self) -> usize {
        self.nqubits
    }

    /// Return canonical terms.
    pub fn terms(&self) -> &[PauliTerm] {
        &self.terms
    }

    /// Add two operators and canonicalize the result.
    pub fn add(&self, other: &Self) -> Result<Self, PauliError> {
        self.ensure_compatible(other)?;
        let mut structures = Vec::with_capacity(self.terms.len() + other.terms.len());
        let mut coefficients = Vec::with_capacity(structures.capacity());
        for term in self.terms.iter().chain(&other.terms) {
            structures.push(term.word.codes());
            coefficients.push(term.coefficient);
        }
        Self::from_terms(self.nqubits, &structures, &coefficients)
    }

    /// Scale all coefficients by a finite complex scalar.
    pub fn scale(&self, scalar: Complex64) -> Result<Self, PauliError> {
        if !scalar.re.is_finite() || !scalar.im.is_finite() {
            return Err(PauliError::NonFiniteCoefficient { index: 0 });
        }
        let mut result = self.clone();
        for term in &mut result.terms {
            term.coefficient *= scalar;
        }
        Ok(result)
    }

    /// Multiply two canonical operators with exact Pauli phases.
    pub fn multiply(&self, other: &Self) -> Result<Self, PauliError> {
        self.ensure_compatible(other)?;
        let mut structures = Vec::with_capacity(self.terms.len() * other.terms.len());
        let mut coefficients = Vec::with_capacity(structures.capacity());
        for left in &self.terms {
            for right in &other.terms {
                let (word, phase) = left.word.multiply(&right.word)?;
                structures.push(word.codes());
                coefficients.push(left.coefficient * right.coefficient * phase.as_complex());
            }
        }
        Self::from_terms(self.nqubits, &structures, &coefficients)
    }

    /// Compute `[self, other]`.
    pub fn commutator(&self, other: &Self) -> Result<Self, PauliError> {
        self.multiply(other)?
            .add(&other.multiply(self)?.scale(Complex64::new(-1.0, 0.0))?)
    }

    /// Compute `{self, other}`.
    pub fn anticommutator(&self, other: &Self) -> Result<Self, PauliError> {
        self.multiply(other)?.add(&other.multiply(self)?)
    }

    /// Return the adjoint operator.
    pub fn adjoint(&self) -> Self {
        Self {
            nqubits: self.nqubits,
            terms: self
                .terms
                .iter()
                .map(|term| PauliTerm {
                    word: term.word.adjoint(),
                    coefficient: term.coefficient.conj(),
                })
                .collect(),
        }
    }

    /// Check exact Hermiticity or Hermiticity within an explicit tolerance.
    pub fn is_hermitian(&self, tolerance: f64) -> bool {
        if !tolerance.is_finite() || tolerance < 0.0 {
            return false;
        }
        self.terms.iter().all(|term| {
            let difference = term.coefficient - term.coefficient.conj();
            difference.norm_sqr() <= tolerance * tolerance
        })
    }

    fn ensure_compatible(&self, other: &Self) -> Result<(), PauliError> {
        if self.nqubits != other.nqubits {
            return Err(PauliError::IncompatibleQubitCounts {
                left: self.nqubits,
                right: other.nqubits,
            });
        }
        Ok(())
    }

    /// Compile a dense row-major matrix using qubit zero as the MSB.
    pub fn dense_matrix(&self, max_bytes: u128) -> Result<(usize, Vec<Complex64>), PauliError> {
        let dimension = matrix_dimension(self.nqubits)?;
        let entries = dimension
            .checked_mul(dimension)
            .ok_or(PauliError::Overflow {
                context: "estimating dense matrix entries",
            })?;
        check_allocation(entries as u128 * 16, max_bytes)?;
        let terms = self
            .terms
            .iter()
            .map(matrix_term)
            .collect::<Result<Vec<_>, _>>()?;
        let mut matrix = vec![Complex64::default(); entries];
        let work = terms.len().saturating_mul(dimension);
        if work >= 1 << 16 {
            matrix
                .par_chunks_mut(dimension)
                .enumerate()
                .for_each(|(row, output)| {
                    for term in &terms {
                        let column = row ^ term.x_mask;
                        let contribution = term.weighted_phase;
                        if (term.z_mask & column).count_ones() & 1 == 0 {
                            output[column] += contribution;
                        } else {
                            output[column] -= contribution;
                        }
                    }
                });
        } else {
            for (row, output) in matrix.chunks_exact_mut(dimension).enumerate() {
                for term in &terms {
                    let column = row ^ term.x_mask;
                    let contribution = term.weighted_phase;
                    if (term.z_mask & column).count_ones() & 1 == 0 {
                        output[column] += contribution;
                    } else {
                        output[column] -= contribution;
                    }
                }
            }
        }
        Ok((dimension, matrix))
    }

    /// Compile deterministic, duplicate-aggregated COO entries.
    pub fn coo_matrix(&self, max_bytes: u128) -> Result<CooMatrix, PauliError> {
        let (dimension, groups, upper_bound) = self.matrix_groups()?;
        let output_bytes = (2 * size_of::<u64>() + size_of::<Complex64>()) as u128;
        if groups.iter().all(|group| group.terms.len() == 1) {
            check_allocation(
                (upper_bound as u128)
                    .checked_mul(output_bytes)
                    .ok_or(PauliError::Overflow {
                        context: "estimating direct COO output memory",
                    })?,
                max_bytes,
            )?;
            let (rows, columns, values) = direct_coo_arrays(&groups, upper_bound);
            return Ok(CooMatrix {
                dimension,
                rows,
                columns,
                values,
            });
        }
        let candidate_bytes = size_of::<SparseEntry>() as u128;
        let row_count_bytes = (dimension as u128)
            .checked_mul(size_of::<usize>() as u128)
            .ok_or(PauliError::Overflow {
                context: "estimating COO row-count memory",
            })?;
        check_allocation(
            (upper_bound as u128)
                .checked_mul(candidate_bytes + output_bytes)
                .and_then(|bytes| bytes.checked_add(row_count_bytes))
                .ok_or(PauliError::Overflow {
                    context: "estimating COO working memory",
                })?,
            max_bytes,
        )?;
        let sparse = sparse_entries(dimension, &groups, upper_bound);
        let entry_count = sparse.entries.len();
        let mut rows = Vec::with_capacity(entry_count);
        let mut columns = Vec::with_capacity(entry_count);
        let mut values = Vec::with_capacity(entry_count);
        let mut offset = 0;
        for (row, &count) in sparse.row_counts.iter().enumerate() {
            for _ in 0..count {
                rows.push(row as u64);
            }
            for entry in &sparse.entries[offset..offset + count] {
                columns.push(entry.column);
                values.push(entry.value);
            }
            offset += count;
        }
        Ok(CooMatrix {
            dimension,
            rows,
            columns,
            values,
        })
    }

    /// Compile deterministic CSR from the canonical COO stream.
    pub fn csr_matrix(&self, max_bytes: u128) -> Result<CsrMatrix, PauliError> {
        let (dimension, groups, upper_bound) = self.matrix_groups()?;
        let output_bytes = (size_of::<u64>() as u128)
            .checked_mul((dimension + 1) as u128)
            .and_then(|indptr_bytes| {
                (size_of::<u64>() as u128 + size_of::<Complex64>() as u128)
                    .checked_mul(upper_bound as u128)
                    .and_then(|entries_bytes| indptr_bytes.checked_add(entries_bytes))
            })
            .ok_or(PauliError::Overflow {
                context: "estimating CSR working memory",
            })?;
        if groups.iter().all(|group| group.terms.len() == 1) {
            check_allocation(output_bytes, max_bytes)?;
            let (indptr, columns, values) = direct_csr_arrays(dimension, &groups, upper_bound);
            return Ok(CsrMatrix {
                dimension,
                indptr,
                columns,
                values,
            });
        }
        let candidate_bytes = size_of::<SparseEntry>() as u128;
        let row_count_bytes = (dimension as u128)
            .checked_mul(size_of::<usize>() as u128)
            .ok_or(PauliError::Overflow {
                context: "estimating CSR row-count memory",
            })?;
        check_allocation(
            (upper_bound as u128)
                .checked_mul(candidate_bytes)
                .and_then(|candidate| candidate.checked_add(output_bytes))
                .and_then(|bytes| bytes.checked_add(row_count_bytes))
                .ok_or(PauliError::Overflow {
                    context: "estimating CSR working memory",
                })?,
            max_bytes,
        )?;
        let sparse = sparse_entries(dimension, &groups, upper_bound);
        let mut indptr = vec![0_u64; dimension + 1];
        for (row, &count) in sparse.row_counts.iter().enumerate() {
            indptr[row + 1] = count as u64;
        }
        for row in 1..indptr.len() {
            indptr[row] += indptr[row - 1];
        }
        let mut columns = Vec::with_capacity(sparse.entries.len());
        let mut values = Vec::with_capacity(sparse.entries.len());
        for entry in sparse.entries {
            columns.push(entry.column);
            values.push(entry.value);
        }
        Ok(CsrMatrix {
            dimension,
            indptr,
            columns,
            values,
        })
    }

    /// Apply the operator without materializing a matrix.
    pub fn mvp(&self, state: &[Complex64], max_bytes: u128) -> Result<Vec<Complex64>, PauliError> {
        MvpPlan::from_operator(self)?.apply(state, max_bytes)
    }

    /// Apply a one-shot matrix-free plan into caller-owned storage.
    pub fn mvp_into(
        &self,
        state: &[Complex64],
        result: &mut [Complex64],
        max_bytes: u128,
    ) -> Result<(), PauliError> {
        MvpPlan::from_operator(self)?.apply_into(state, result, max_bytes)
    }

    /// Compile a reusable CPU matrix-free application plan.
    pub fn mvp_plan(&self, max_bytes: u128) -> Result<MvpPlan, PauliError> {
        MvpPlan::from_operator_reusable(self, max_bytes)
    }

    /// Return a versioned pure-array backend MVP plan.
    pub fn backend_mvp_plan(&self, max_bytes: u128) -> Result<BackendMvpPlan, PauliError> {
        let word_count = packed_word_count(self.nqubits);
        let bytes = (self.terms.len() as u128)
            .checked_mul((word_count as u128).saturating_mul(16).saturating_add(16))
            .ok_or(PauliError::Overflow {
                context: "estimating backend plan bytes",
            })?;
        check_allocation(bytes, max_bytes)?;
        let mut x_words = Vec::with_capacity(self.terms.len() * word_count);
        let mut z_words = Vec::with_capacity(self.terms.len() * word_count);
        let mut coefficients = Vec::with_capacity(self.terms.len());
        for term in &self.terms {
            x_words.extend_from_slice(term.word.x_words());
            z_words.extend_from_slice(term.word.z_words());
            coefficients.push(term.coefficient);
        }
        Ok(BackendMvpPlan {
            nqubits: self.nqubits,
            word_count,
            x_words,
            z_words,
            coefficients,
        })
    }

    fn matrix_groups(&self) -> Result<(usize, Vec<MatrixGroup>, usize), PauliError> {
        let dimension = matrix_dimension(self.nqubits)?;
        let terms = self
            .terms
            .iter()
            .map(matrix_term)
            .collect::<Result<Vec<_>, _>>()?;
        let groups = group_matrix_terms(terms);
        let upper_bound = groups
            .len()
            .checked_mul(dimension)
            .ok_or(PauliError::Overflow {
                context: "estimating sparse matrix entries",
            })?;
        Ok((dimension, groups, upper_bound))
    }
}

fn matrix_dimension(nqubits: usize) -> Result<usize, PauliError> {
    if nqubits >= usize::BITS as usize {
        return Err(PauliError::Overflow {
            context: "computing matrix dimension",
        });
    }
    1_usize
        .checked_shl(nqubits as u32)
        .ok_or(PauliError::Overflow {
            context: "computing matrix dimension",
        })
}

fn check_allocation(requested: u128, limit: u128) -> Result<(), PauliError> {
    if requested > limit {
        return Err(PauliError::MemoryLimit { requested, limit });
    }
    Ok(())
}

fn matrix_term(term: &PauliTerm) -> Result<MatrixTerm, PauliError> {
    let word = &term.word;
    if word.nqubits >= usize::BITS as usize {
        return Err(PauliError::Overflow {
            context: "converting matrix X mask",
        });
    }
    let mut x_mask = 0_usize;
    let mut z_mask = 0_usize;
    let mut y_count = 0_u32;
    for qubit in 0..word.nqubits {
        let packed_mask = 1_u64 << (qubit % 64);
        let x = word.x_words[qubit / 64] & packed_mask != 0;
        let z = word.z_words[qubit / 64] & packed_mask != 0;
        let matrix_mask = 1_usize << (word.nqubits - 1 - qubit);
        if x {
            x_mask |= matrix_mask;
        }
        if z {
            z_mask |= matrix_mask;
        }
        if x && z {
            y_count += 1;
        }
    }
    let y_phase = match y_count % 4 {
        0 => Complex64::new(1.0, 0.0),
        1 => Complex64::new(0.0, 1.0),
        2 => Complex64::new(-1.0, 0.0),
        _ => Complex64::new(0.0, -1.0),
    };
    Ok(MatrixTerm {
        x_mask,
        z_mask,
        weighted_phase: term.coefficient * y_phase,
    })
}

fn group_matrix_terms(terms: Vec<MatrixTerm>) -> Vec<MatrixGroup> {
    let mut grouped = BTreeMap::<usize, Vec<MatrixTerm>>::new();
    for term in terms {
        grouped.entry(term.x_mask).or_default().push(term);
    }
    grouped
        .into_iter()
        .map(|(x_mask, terms)| MatrixGroup { x_mask, terms })
        .collect()
}

fn sparse_entries(dimension: usize, groups: &[MatrixGroup], upper_bound: usize) -> SparseEntries {
    let width = groups.len();
    let mut entries = vec![SparseEntry::default(); upper_bound];
    let mut row_counts = vec![0_usize; dimension];
    if width == 0 {
        return SparseEntries {
            entries,
            row_counts,
        };
    }

    if upper_bound >= 1 << 18 {
        entries
            .par_chunks_mut(width)
            .zip(row_counts.par_iter_mut())
            .enumerate()
            .for_each(|(row, (output, count))| {
                *count = fill_sparse_row(row, groups, output);
            });
    } else {
        for (row, (output, count)) in entries
            .chunks_exact_mut(width)
            .zip(row_counts.iter_mut())
            .enumerate()
        {
            *count = fill_sparse_row(row, groups, output);
        }
    }

    let mut write = 0;
    for (row, &count) in row_counts.iter().enumerate() {
        let start = row * width;
        if count != 0 {
            entries.copy_within(start..start + count, write);
            write += count;
        }
    }
    entries.truncate(write);
    SparseEntries {
        entries,
        row_counts,
    }
}

fn direct_coo_arrays(
    groups: &[MatrixGroup],
    upper_bound: usize,
) -> (Vec<u64>, Vec<u64>, Vec<Complex64>) {
    let width = groups.len();
    if width == 0 {
        return (Vec::new(), Vec::new(), Vec::new());
    }
    let mut rows = vec![0_u64; upper_bound];
    let mut columns = vec![0_u64; upper_bound];
    let mut values = vec![Complex64::default(); upper_bound];
    if upper_bound >= 1 << 18 {
        rows.par_chunks_mut(width)
            .zip(columns.par_chunks_mut(width))
            .zip(values.par_chunks_mut(width))
            .enumerate()
            .for_each_init(
                || Vec::with_capacity(width),
                |scratch, (row, ((row_output, column_output), value_output))| {
                    scratch.clear();
                    scratch.resize(width, SparseEntry::default());
                    fill_sparse_row(row, groups, scratch);
                    row_output.fill(row as u64);
                    for (index, entry) in scratch.iter().enumerate() {
                        column_output[index] = entry.column;
                        value_output[index] = entry.value;
                    }
                },
            );
    } else {
        let mut scratch = vec![SparseEntry::default(); width];
        for (row, ((row_output, column_output), value_output)) in rows
            .chunks_exact_mut(width)
            .zip(columns.chunks_exact_mut(width))
            .zip(values.chunks_exact_mut(width))
            .enumerate()
        {
            fill_sparse_row(row, groups, &mut scratch);
            row_output.fill(row as u64);
            for (index, entry) in scratch.iter().enumerate() {
                column_output[index] = entry.column;
                value_output[index] = entry.value;
            }
        }
    }
    (rows, columns, values)
}

fn direct_csr_arrays(
    dimension: usize,
    groups: &[MatrixGroup],
    upper_bound: usize,
) -> (Vec<u64>, Vec<u64>, Vec<Complex64>) {
    let width = groups.len();
    let mut indptr = vec![0_u64; dimension + 1];
    if width == 0 {
        return (indptr, Vec::new(), Vec::new());
    }
    for (row, pointer) in indptr.iter_mut().enumerate() {
        *pointer = (row * width) as u64;
    }
    let mut columns = vec![0_u64; upper_bound];
    let mut values = vec![Complex64::default(); upper_bound];
    if upper_bound >= 1 << 18 {
        columns
            .par_chunks_mut(width)
            .zip(values.par_chunks_mut(width))
            .enumerate()
            .for_each_init(
                || Vec::with_capacity(width),
                |scratch, (row, (column_output, value_output))| {
                    scratch.clear();
                    scratch.resize(width, SparseEntry::default());
                    fill_sparse_row(row, groups, scratch);
                    for (index, entry) in scratch.iter().enumerate() {
                        column_output[index] = entry.column;
                        value_output[index] = entry.value;
                    }
                },
            );
    } else {
        let mut scratch = vec![SparseEntry::default(); width];
        for (row, (column_output, value_output)) in columns
            .chunks_exact_mut(width)
            .zip(values.chunks_exact_mut(width))
            .enumerate()
        {
            fill_sparse_row(row, groups, &mut scratch);
            for (index, entry) in scratch.iter().enumerate() {
                column_output[index] = entry.column;
                value_output[index] = entry.value;
            }
        }
    }
    (indptr, columns, values)
}

fn fill_sparse_row(row: usize, groups: &[MatrixGroup], output: &mut [SparseEntry]) -> usize {
    let mut count = 0;
    for group in groups {
        let column = row ^ group.x_mask;
        let mut value = Complex64::default();
        for term in &group.terms {
            let mut contribution = term.weighted_phase;
            if (term.z_mask & column).count_ones() & 1 != 0 {
                contribution = -contribution;
            }
            value += contribution;
        }
        if !value.is_zero() {
            output[count] = SparseEntry {
                column: column as u64,
                value,
            };
            count += 1;
        }
    }
    sort_sparse_row(&mut output[..count]);
    count
}

fn sort_sparse_row(entries: &mut [SparseEntry]) {
    match entries.len() {
        0 | 1 => {}
        2 => {
            if entries[0].column > entries[1].column {
                entries.swap(0, 1);
            }
        }
        3 => {
            if entries[0].column > entries[1].column {
                entries.swap(0, 1);
            }
            if entries[1].column > entries[2].column {
                entries.swap(1, 2);
            }
            if entries[0].column > entries[1].column {
                entries.swap(0, 1);
            }
        }
        _ => entries.sort_unstable_by_key(|entry| entry.column),
    }
}

/// Convert a qubit count to a packed word count without integer overflow.
pub fn packed_word_count(nqubits: usize) -> usize {
    nqubits / 64 + usize::from(nqubits % 64 != 0)
}

fn final_word_mask(nqubits: usize) -> Option<u64> {
    let remainder = nqubits % 64;
    (remainder != 0).then(|| (1_u64 << remainder) - 1)
}

fn code_bits(code: u8, index: usize) -> Result<(u64, u64), PauliError> {
    match code {
        0 => Ok((0, 0)),
        1 => Ok((1, 0)),
        2 => Ok((1, 1)),
        3 => Ok((0, 1)),
        _ => Err(PauliError::InvalidCode { code, index }),
    }
}

fn local_product(left: u8, right: u8) -> (u8, PauliPhase) {
    match (left, right) {
        (0, code) | (code, 0) => (code, PauliPhase::PlusOne),
        (1, 1) | (2, 2) | (3, 3) => (0, PauliPhase::PlusOne),
        (1, 2) => (3, PauliPhase::PlusI),
        (2, 1) => (3, PauliPhase::MinusI),
        (1, 3) => (2, PauliPhase::MinusI),
        (3, 1) => (2, PauliPhase::PlusI),
        (2, 3) => (1, PauliPhase::PlusI),
        (3, 2) => (1, PauliPhase::MinusI),
        _ => unreachable!("PauliWord validates local codes before multiplication"),
    }
}

#[cfg(test)]
mod tests {
    use super::{Complex64, PauliOperator, PauliPhase, PauliWord};

    #[test]
    fn computes_weight_and_canonicalizes_unused_bits() {
        let word = PauliWord::from_words(2, vec![u64::MAX], vec![0]).unwrap();
        assert_eq!(word.x_words(), &[0b11]);
        assert_eq!(word.weight(), 2);
    }

    #[test]
    fn checks_symplectic_commutation() {
        let x0 = PauliWord::from_words(2, vec![0b01], vec![0]).unwrap();
        let z0 = PauliWord::from_words(2, vec![0], vec![0b01]).unwrap();
        let xx = PauliWord::from_words(2, vec![0b11], vec![0]).unwrap();
        let zz = PauliWord::from_words(2, vec![0], vec![0b11]).unwrap();
        assert!(!x0.commutes_with(&z0).unwrap());
        assert!(xx.commutes_with(&zz).unwrap());
    }

    #[test]
    fn covers_phase_table_and_round_trip() {
        let expected = [
            (1, 2, 3, PauliPhase::PlusI),
            (2, 1, 3, PauliPhase::MinusI),
            (1, 3, 2, PauliPhase::MinusI),
            (3, 1, 2, PauliPhase::PlusI),
            (2, 3, 1, PauliPhase::PlusI),
            (3, 2, 1, PauliPhase::MinusI),
        ];
        for (left, right, result, phase) in expected {
            let left_word = PauliWord::from_codes(1, &[left]).unwrap();
            let right_word = PauliWord::from_codes(1, &[right]).unwrap();
            let (actual, actual_phase) = left_word.multiply(&right_word).unwrap();
            assert_eq!(actual.codes(), vec![result]);
            assert_eq!(actual_phase, phase);
        }
        let word = PauliWord::from_codes(130, &[2; 130]).unwrap();
        assert_eq!(word.codes(), vec![2; 130]);
    }

    #[test]
    fn canonical_operator_algebra_aggregates_exact_zeros() {
        let operator = PauliOperator::from_terms(
            1,
            &[vec![1], vec![1], vec![2]],
            &[
                Complex64::new(1.0, 0.0),
                Complex64::new(-1.0, 0.0),
                Complex64::new(2.0, 0.0),
            ],
        )
        .unwrap();
        assert_eq!(operator.terms().len(), 1);
        assert!(operator.is_hermitian(0.0));
        let reversed = PauliOperator::from_terms(
            1,
            &[vec![2], vec![1], vec![1]],
            &[
                Complex64::new(2.0, 0.0),
                Complex64::new(-1.0, 0.0),
                Complex64::new(1.0, 0.0),
            ],
        )
        .unwrap();
        let reordered = PauliOperator::from_terms(
            1,
            &[vec![1], vec![2], vec![1]],
            &[
                Complex64::new(1.0, 0.0),
                Complex64::new(2.0, 0.0),
                Complex64::new(-1.0, 0.0),
            ],
        )
        .unwrap();
        assert_eq!(reversed, reordered);
    }
}
