use std::cmp::Ordering;

use crate::error::PauliError;
use crate::scalar::Complex64;

/// The exact phase generated by multiplying two Hermitian Pauli words.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PauliPhase {
    /// `+1`.
    PlusOne,
    /// `+i`.
    PlusI,
    /// `-1`.
    MinusOne,
    /// `-i`.
    MinusI,
}

impl PauliPhase {
    /// Return the phase as a complex128-compatible value.
    pub const fn as_complex(self) -> Complex64 {
        match self {
            Self::PlusOne => Complex64::new(1.0, 0.0),
            Self::PlusI => Complex64::new(0.0, 1.0),
            Self::MinusOne => Complex64::new(-1.0, 0.0),
            Self::MinusI => Complex64::new(0.0, -1.0),
        }
    }

    fn exponent(self) -> u8 {
        match self {
            Self::PlusOne => 0,
            Self::PlusI => 1,
            Self::MinusOne => 2,
            Self::MinusI => 3,
        }
    }

    fn from_exponent(exponent: u8) -> Self {
        match exponent % 4 {
            0 => Self::PlusOne,
            1 => Self::PlusI,
            2 => Self::MinusOne,
            _ => Self::MinusI,
        }
    }

    fn multiply(self, rhs: Self) -> Self {
        Self::from_exponent(self.exponent() + rhs.exponent())
    }
}

/// A phase-free Pauli word in binary symplectic representation.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct PauliWord {
    pub(crate) nqubits: usize,
    pub(crate) x_words: Vec<u64>,
    pub(crate) z_words: Vec<u64>,
}

impl PauliWord {
    /// Build and canonicalize a word from packed little-endian masks.
    pub fn from_words(
        nqubits: usize,
        mut x_words: Vec<u64>,
        mut z_words: Vec<u64>,
    ) -> Result<Self, PauliError> {
        let expected = packed_word_count(nqubits);
        if x_words.len() != expected {
            return Err(PauliError::InvalidWordLength {
                expected,
                actual: x_words.len(),
            });
        }
        if z_words.len() != expected {
            return Err(PauliError::InvalidWordLength {
                expected,
                actual: z_words.len(),
            });
        }
        if let Some(mask) = final_word_mask(nqubits) {
            let last = expected - 1;
            x_words[last] &= mask;
            z_words[last] &= mask;
        }
        Ok(Self {
            nqubits,
            x_words,
            z_words,
        })
    }

    /// Build a word from external I/X/Y/Z codes.
    pub fn from_codes(nqubits: usize, codes: &[u8]) -> Result<Self, PauliError> {
        if codes.len() != nqubits {
            return Err(PauliError::InvalidStructureLength {
                expected: nqubits,
                actual: codes.len(),
            });
        }
        let word_count = packed_word_count(nqubits);
        let mut x_words = vec![0; word_count];
        let mut z_words = vec![0; word_count];
        for (qubit, &code) in codes.iter().enumerate() {
            let (x, z) = code_bits(code, qubit)?;
            x_words[qubit / 64] |= x << (qubit % 64);
            z_words[qubit / 64] |= z << (qubit % 64);
        }
        Self::from_words(nqubits, x_words, z_words)
    }

    /// Return the number of qubits represented by the word.
    pub fn nqubits(&self) -> usize {
        self.nqubits
    }

    /// Return the packed X masks.
    pub fn x_words(&self) -> &[u64] {
        &self.x_words
    }

    /// Return the packed Z masks.
    pub fn z_words(&self) -> &[u64] {
        &self.z_words
    }

    /// Convert to external I/X/Y/Z codes in qubit order.
    pub fn codes(&self) -> Vec<u8> {
        (0..self.nqubits).map(|qubit| self.code_at(qubit)).collect()
    }

    /// Return the non-identity qubit indices.
    pub fn support(&self) -> Vec<usize> {
        (0..self.nqubits)
            .filter(|&qubit| self.code_at(qubit) != 0)
            .collect()
    }

    /// Return the number of non-identity sites.
    pub fn weight(&self) -> u32 {
        self.x_words
            .iter()
            .zip(&self.z_words)
            .map(|(x_word, z_word)| (x_word | z_word).count_ones())
            .sum()
    }

    /// Return the binary symplectic inner product.
    pub fn symplectic_inner_product(&self, other: &Self) -> Result<u8, PauliError> {
        self.ensure_compatible(other)?;
        let parity = self
            .x_words
            .iter()
            .zip(&self.z_words)
            .zip(&other.x_words)
            .zip(&other.z_words)
            .fold(
                0_u32,
                |accumulator, (((x_left, z_left), x_right), z_right)| {
                    accumulator
                        ^ ((x_left & z_right).count_ones() & 1)
                        ^ ((z_left & x_right).count_ones() & 1)
                },
            );
        Ok((parity & 1) as u8)
    }

    /// Return whether this word commutes with `other`.
    pub fn commutes_with(&self, other: &Self) -> Result<bool, PauliError> {
        Ok(self.symplectic_inner_product(other)? == 0)
    }

    /// Return whether words are compatible for one local measurement basis.
    pub fn qwc_compatible(&self, other: &Self) -> Result<bool, PauliError> {
        self.ensure_compatible(other)?;
        Ok(self
            .x_words
            .iter()
            .zip(&self.z_words)
            .zip(&other.x_words)
            .zip(&other.z_words)
            .all(|(((x_left, z_left), x_right), z_right)| {
                let occupied = (x_left | z_left) & (x_right | z_right);
                let different = (x_left ^ x_right) | (z_left ^ z_right);
                occupied & different == 0
            }))
    }

    /// Multiply two phase-free words and return the exact discrete phase.
    pub fn multiply(&self, other: &Self) -> Result<(Self, PauliPhase), PauliError> {
        self.ensure_compatible(other)?;
        let result = Self::from_words(
            self.nqubits,
            self.x_words
                .iter()
                .zip(&other.x_words)
                .map(|(left, right)| left ^ right)
                .collect(),
            self.z_words
                .iter()
                .zip(&other.z_words)
                .map(|(left, right)| left ^ right)
                .collect(),
        )?;
        let mut phase = PauliPhase::PlusOne;
        for qubit in 0..self.nqubits {
            phase = phase.multiply(local_product(self.code_at(qubit), other.code_at(qubit)).1);
        }
        Ok((result, phase))
    }

    /// Return the adjoint word. Phase-free Pauli basis words are Hermitian.
    pub fn adjoint(&self) -> Self {
        self.clone()
    }

    fn ensure_compatible(&self, other: &Self) -> Result<(), PauliError> {
        if self.nqubits != other.nqubits {
            return Err(PauliError::IncompatibleQubitCounts {
                left: self.nqubits,
                right: other.nqubits,
            });
        }
        Ok(())
    }

    fn code_at(&self, qubit: usize) -> u8 {
        let x = (self.x_words[qubit / 64] >> (qubit % 64)) & 1;
        let z = (self.z_words[qubit / 64] >> (qubit % 64)) & 1;
        match (x, z) {
            (0, 0) => 0,
            (1, 0) => 1,
            (1, 1) => 2,
            (0, 1) => 3,
            _ => unreachable!("packed symplectic bits are binary"),
        }
    }
}

impl Ord for PauliWord {
    fn cmp(&self, other: &Self) -> Ordering {
        let qubit_order = self.nqubits.cmp(&other.nqubits);
        if qubit_order != Ordering::Equal {
            return qubit_order;
        }
        for qubit in 0..self.nqubits {
            let order = self.code_at(qubit).cmp(&other.code_at(qubit));
            if order != Ordering::Equal {
                return order;
            }
        }
        Ordering::Equal
    }
}

impl PartialOrd for PauliWord {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// Convert a qubit count to a packed word count without integer overflow.
pub fn packed_word_count(nqubits: usize) -> usize {
    nqubits / 64 + usize::from(nqubits % 64 != 0)
}

fn final_word_mask(nqubits: usize) -> Option<u64> {
    let remainder = nqubits % 64;
    (remainder != 0).then(|| (1_u64 << remainder) - 1)
}

fn code_bits(code: u8, index: usize) -> Result<(u64, u64), PauliError> {
    match code {
        0 => Ok((0, 0)),
        1 => Ok((1, 0)),
        2 => Ok((1, 1)),
        3 => Ok((0, 1)),
        _ => Err(PauliError::InvalidCode { code, index }),
    }
}

fn local_product(left: u8, right: u8) -> (u8, PauliPhase) {
    match (left, right) {
        (0, code) | (code, 0) => (code, PauliPhase::PlusOne),
        (1, 1) | (2, 2) | (3, 3) => (0, PauliPhase::PlusOne),
        (1, 2) => (3, PauliPhase::PlusI),
        (2, 1) => (3, PauliPhase::MinusI),
        (1, 3) => (2, PauliPhase::MinusI),
        (3, 1) => (2, PauliPhase::PlusI),
        (2, 3) => (1, PauliPhase::PlusI),
        (3, 2) => (1, PauliPhase::MinusI),
        _ => unreachable!("PauliWord validates local codes before multiplication"),
    }
}
